// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace HIV_CARE.Repositories.ThienTTT.Models;

public partial class AppointmentThienTtt
{
    [Key]
    public int AppointmentsThienTttid { get; set; }

    [Required(ErrorMessage = "A doctor must be selected.")]
    public int DoctorsPhatNhid { get; set; }

    [Required(ErrorMessage = "Patient name cannot be empty.")]
    public string PatientName { get; set; }

    [Required(ErrorMessage = "An appointment date must be provided.")]
    public DateTime AppointmentDate { get; set; }

    public string AppointmentTime { get; set; }

    public int EstimatedDuration { get; set; }

    public string ConsultationType { get; set; }

    public int Priority { get; set; }

    public bool IsConfirmed { get; set; }

    public bool IsCompleted { get; set; }

    public bool IsAnonymous { get; set; }

    public decimal TotalFee { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public virtual DoctorPhatNh DoctorsPhatNh { get; set; }
}